/*+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#+
#+     Mumps Bioinformatics Software Library
#+     Copyright (C) 2003, 2004, 2008, 2015, 2017,
#+     2022, 2024  by Kevin C. O'Kane
#+
#+     Kevin C. O'Kane
#+     kc.okane@gmail.com
#+     okane@uni.edu
#+     https://threadsafebooks.com/
#+     https://www.cs.uni.edu/~okane
#+
#+ This program is free software; you can redistribute it and/or modify
#+ it under the terms of the GNU General Public License as published by
#+ the Free Software Foundation; either version 2 of the License, or
#+ (at your option) any later version.
#+
#+ This program is distributed in the hope that it will be useful,
#+ but WITHOUT ANY WARRANTY; without even the implied warranty of
#+ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#+ GNU General Public License for more details.
#+
#+ You should have received a copy of the GNU General Public License
#+ along with this program; if not, write to the Free Software
#+ Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#+
#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*/

//	May 26, 2024

#include <stdio.h>
#include <time.h>

#include <mumpsc/compiler-macros.h>

void	copyright_notice(FILE *Out) {

//#+*+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
//#*
//#* Copyright and Disclaimer to Output File
//#*
//#+*+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

    Sysout ("// ==============================================================\n");

    Sysout ("//#+ This module generated by Mumps Compiler \n");

   time_t curtime; time(&curtime);
   fprintf(Out, "//#+ %s", ctime(&curtime));

    Sysout("//#+ Portions of this code are part of the Mumps Compiler\n");
    Sysout("//#+ \n");
    Sysout("//#+ Copyright (C) 2000, 2001, 2002, 2003, 2004, 2005, \n");
    Sysout("//#+ 2010, 2017, 2020, 2022, 2024 by Kevin C. O'Kane  \n");
    Sysout("//#+ \n");
    Sysout("//#+ Kevin C. O'Kane, Ph.D.\n");
    Sysout("//#+ Professor Emeritus\n");
    Sysout("//#+ Computer Science Department\n");
    Sysout("//#+ University of Northern Iowa\n");
    Sysout("//#+ Cedar Falls, IA 50614-0507\n");
    Sysout("//#+ kc.okane@gmail.com\n");
    Sysout("//#+ okane@uni.edu\n");
    Sysout("//#+ https://threadsafebooks.com\n");
    Sysout("//#+ https://www.cs.uni.edu/~okane\n");
    Sysout("//#+ -----------------------------------\n");
    Sysout("//#+ \n");
    Sysout("//#+ Consult individual modules for copyright details\n");
    Sysout("//#+ The runtime libraries are covered by the following license:\n");
    Sysout("//#+  \n");
    Sysout("//#+ This library is free software; you can redistribute it and/or\n");
    Sysout("//#+ modify it under the terms of the GNU Lesser General Public\n");
    Sysout("//#+ License as published by the Free Software Foundation; either\n");
    Sysout("//#+ version 2.1 of the License, or (at your option) any later version.\n");
    Sysout("//#+ \n");
    Sysout("//#+ This library is distributed in the hope that it will be useful,\n");
    Sysout("//#+ but WITHOUT ANY WARRANTY; without even the implied warranty of\n");
    Sysout("//#+ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU\n");
    Sysout("//#+ Lesser General Public License for more details.\n");
    Sysout("//#+ \n");
    Sysout("//#+ You should have received a copy of the GNU Lesser General Public\n");
    Sysout("//#+ License along with this library; if not, write to the Free Software\n");
    Sysout("//#+ Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA\n");
    Sysout("//#+ \n");
    Sysout("//#+ This code is unverified - use at your own risk \n");
    Sysout("//#+==============================================================\n");
    Sysout("\n");

	}
