#!/bin/bash

#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#+
#+     Mumps Bioinformatics Software Library
#+     Copyright (C) 2015 - 2026 by Kevin C. O'Kane
#+
#+     Kevin C. O'Kane
#+     kc.okane@gmail.com
#+     https://threadsafebooks.com/
#+     https://www.cs.uni.edu/~okane
#+
#+ This program is free software; you can redistribute it and/or modify
#+ it under the terms of the GNU General Public License as published by
#+ the Free Software Foundation; either version 2 of the License, or
#+ (at your option) any later version.
#+
#+ This program is distributed in the hope that it will be useful,
#+ but WITHOUT ANY WARRANTY; without even the implied warranty of
#+ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#+ GNU General Public License for more details.
#+
#+ You should have received a copy of the GNU General Public License
#+ along with this program; if not, write to the Free Software
#+ Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#+
#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

# Feb 14, 2026

# this file MUST be run as root
# this file MUST be run as root
# this file MUST be run as root

if [ `whoami` != "root" ]; then
	echo
	echo "****************************************"
        echo "**** you must be root to run this script"
	echo "****************************************"
	echo
        exit
        fi

# This file will install (if needed) Sqlite3 and other libraries and 
# configure them

echo
echo "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv"
echo "Grand general Mumps Sqlite3 instalerizer."
echo "This script will install, as needed, Sqlite3, g++,"
echo "autoconf, libccre-dev etc."
echo "^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^"
echo

	apt-get -q update
	apt-get -q -y install make
	apt-get -q -y install astyle
	apt-get -q -y install sqlite3
	apt-get -q -y install libsqlite3-dev

	apt-get -q -y install autoconf 

	apt-get -q -y install libreadline-dev

	apt-get -q -y install g++ 
	apt-get -q -y install gcc-doc 

	apt-get -q -y install libgmp-dev
	apt-get -q -y install libmpfr-dev

        apt-get -q -y install libglib2.0-dev
        apt-get -q -y install pkg-config

        apt-get --yes install libgtk-3-dev
        apt-get --yes install libgtkmm-2.4-dev
        apt-get --yes install libgtkmm-3.0-dev
        apt-get --yes install libgtk-3-0
        apt-get --yes install gtk-3-examples
        apt-get  --yes install libwebkit2gtk-4.1-dev
	apt-get --yes install glade

echo
echo "You now should to execute the configure/compile script"

exit

