#!/bin/bash

#*++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#+
#+     Internet Radio Automation & Encoding Toolkit
#+
#+     Copyright (C) 
#+	2018, 2019, 2020, 2021, 2022, 2023 by Kevin C. O'Kane
#+
#+     Kevin C. O'Kane
#+     kc.okane@gmail.com
#+     https://www.cs.uni.edu/~okane
#+     https://threadsafebooks.com/
#+
#+ This program is free software; you can redistribute it and/or modify
#+ it under the terms of the GNU General Public License as published by
#+ the Free Software Foundation; either version 2 of the License, or
#+ (at your option) any later version.
#+
#+ This program is distributed in the hope that it will be useful,
#+ but WITHOUT ANY WARRANTY; without even the implied warranty of
#+ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#+ GNU General Public License for more details.
#+
#+ You should have received a copy of the GNU General Public License
#+ along with this program; if not, write to the Free Software
#+ Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
#+
#+ May 8, 2023
#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

echo
date

echo
echo "Example retrieve sequences"
echo

if [ -z $1 ]
        then
                echo "File containing query not supplied. Using tstquery instead"
		query="tstquery"
        else
		echo "Query containd in file $1"
		query=$1
        fi

cpu_count=`grep processor /proc/cpuinfo | wc -l`
echo "Number or processing elements: $cpu_count"

echo
echo "Query: "
cat $query
echo
echo "Searching ..."

code/starttime.mps

for (( i=0 ; i<$cpu_count ; i++ ));
        do
	cd seg$i
	rm -f *.rslt
	cp ../$query tstquery
	cp ../code/RetrieveGenomeMumps .
	RetrieveGenomeMumps < tstquery > rslt &
	cd ..
	done

wait

ls seg0/*.rslt > rslt.tmp1

for (( i=1 ; i<$cpu_count ; i++ ));
        do
	ls seg$i/*.rslt >> rslt.tmp1
	done

sort -t / -k 2 < rslt.tmp1 | tail -10 > rslt.tmp2

code/show-rslts.mps < rslt.tmp2

rm rslt.tmp1 rslt.tmp2

for (( i=0 ; i<$cpu_count ; i++ ));
        do
	rm -f seg$i/*.rslt
	rm -f seg$i/rslt
	rm -f seg$i/*.tmp
	rm -f seg$i/tstquery
	rm -f seg$i/full.seq
	done

code/endtime.mps
